### ISSUE TITLE
Problem.

### ISSUE THREAD

**Issue by kb9mwr** [Xuth/tp4000_dmm#2]
pi@raspberrypi ~ $ python tp4000zc.py
Traceback (most recent call last):
  File "tp4000zc.py", line 359, in <module>
    main()
  File "tp4000zc.py", line 350, in main
    dmm = Dmm()
  File "tp4000zc.py", line 103, in __init__
    self._synchronize()
  File "tp4000zc.py", line 153, in _synchronize
    raise DmmNoData()
__main__.DmmNoData: <__main__.DmmNoData instance at 0xb6c32850>

**Comment by Xuth** [comment]
The error message is saying that this is not finding the data it's looking for.  Are the serial port settings correct?  Is this the right port?

**Comment by kb9mwr** [comment]
Yes, /dev/ttyUSB0

This does work: https://github.com/coddingtonbear/python-fs9721  However I like yours if I could get it to work as it's more simplistic, and all I need is a one shot reading not a continuous sampling.

**Comment by kb9mwr** [comment]
Nevermind silly me, it just needs root access to read the meter.

**Comment by Xuth** [comment]
Ah... or you can give yourself group access to whatever group the ttys are in.

**Comment by Xuth** [comment]
Thinking about this more, the code probably should have gotten some real error message from pyserial and I would have done well to propagate that error rather than burying it in an opaque "I can't get data error".
